"""Rebuild `autopilot/fonts.py`: the page typefaces, embedded.

An operator page must render identically with no network at all — mailed,
printed, or opened cold three weeks later — so the faces ship inside it.

The faces are embedded exactly as Google serves them, with their variable axes
and full Latin coverage intact. They are deliberately *not* subset: these pages
are written to disk and opened from disk, so the bytes buy nothing, while
subsetting would clip the glyph set to whatever list we guessed at (silently
dropping an unlisted character to the fallback face mid-word) and would pin
Newsreader's optical-size axis, which is what lets one file set both a 3.5rem
title and a 1.3rem standfirst well.

What *is* worth removing is duplication. Google's stylesheet declares one
`@font-face` per weight and per Unicode subset, but a variable family answers
several of those with the same file — Newsreader's roman covers 400 and 600,
and its Latin file covers latin-ext too. Embedding per declaration stores that
file four times. Here each distinct file is embedded once, declared with the
weight range it actually spans. `unicode-range` stays: latin and
latin-ext really are separate files, and without it two faces with identical
descriptors would shadow each other, leaving one embedded and never used.

    python3 tools/build_fonts.py

Reaches the network. The generated module is committed, so this runs only when
the faces change.
"""

from __future__ import annotations

import base64
import re
import urllib.request
from pathlib import Path

UA = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
                    "(KHTML, like Gecko) Chrome/122.0 Safari/537.36"}

FAMILIES = [
    ("Newsreader", "ital,opsz,wght@0,6..72,400;0,6..72,600;1,6..72,400"),
    ("IBM+Plex+Sans", "wght@400;500;600"),
    ("IBM+Plex+Mono", "wght@400;500"),
]
# Latin and its extension: between them they cover the Western names and terms
# a plan or a proof carries. A character outside both falls back to the stack
# declared beside each face, which is a readable face, not a missing glyph.
SUBSETS = ("latin", "latin-ext")


def build() -> str:
    faces, total = {}, 0
    for family, axis in FAMILIES:
        url = f"https://fonts.googleapis.com/css2?family={family}:{axis}&display=swap"
        css = urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=30).read().decode()
        for label, block in re.findall(r"/\* ([\w-]+) \*/\s*@font-face \{(.*?)\}", css, re.S):
            if label not in SUBSETS:
                continue
            name = re.search(r"font-family: '([^']+)'", block).group(1)
            style = re.search(r"font-style: (\w+)", block).group(1)
            weight = re.search(r"font-weight: ([\d ]+)", block).group(1).strip()
            ranges = re.search(r"unicode-range: ([^;]+);", block).group(1).strip()
            source = re.search(r"url\((https://[^)]+)\)", block).group(1)
            entry = faces.setdefault(
                source, {"name": name, "style": style, "weights": set(), "ranges": []}
            )
            entry["weights"].add(int(weight))
            for part in ranges.split(","):
                part = part.strip()
                if part and part not in entry["ranges"]:
                    entry["ranges"].append(part)

    payloads = []
    for source, entry in faces.items():
        data = urllib.request.urlopen(urllib.request.Request(source, headers=UA), timeout=30).read()
        total += len(data)
        low, high = min(entry["weights"]), max(entry["weights"])
        span = str(low) if low == high else f"{low} {high}"
        payloads.append((entry["name"], entry["style"], span, ", ".join(entry["ranges"]),
                         base64.b64encode(data).decode()))
        print(f"{entry['name']:16s} {entry['style']:7s} {span:9s} "
              f"{len(entry['ranges']):3d} ranges {len(data) // 1024:4d} KB")
    print(f"\n{len(payloads)} distinct files, {total // 1024} KB "
          f"({total * 4 // 3 // 1024} KB as base64)")

    header = (
        '"""The page typefaces, embedded.\n\n'
        "Newsreader sets the display type, IBM Plex Sans the running text, and IBM\n"
        "Plex Mono the labels and code. They are inlined rather than linked because an\n"
        "operator page must render identically with no network at all.\n\n"
        'Generated by tools/build_fonts.py; do not edit by hand.\n"""\n\nFONT_FACES = """'
    )
    body = "\n".join(
        "@font-face{font-family:'%s';font-style:%s;font-weight:%s;font-display:swap;"
        "unicode-range:%s;src:url(data:font/woff2;base64,%s) format('woff2')}" % face
        for face in payloads
    )
    return f"{header}\n{body}\n\"\"\"\n"


if __name__ == "__main__":
    target = Path(__file__).resolve().parents[1] / "skills/autopilot/lib/autopilot/fonts.py"
    target.write_text(build())
    print(f"wrote {target} ({target.stat().st_size // 1024} KB)")
